version: '3.7'

services:
  app:
    build: .
    container_name: nuxt-app
    restart: always
    volumes:
      - "/home/ubuntu/data/accum_runs/:/var/www/dockerize-nuxt/nuxt-app/public/data/accum_runs"
    ports:
      - '3010:3010'
    command: 'npm start'

  nginx:
    build: ./nginx
    ports:
      - '80:80'
    depends_on:
      - app
